# Generated by Django 2.0.3 on 2018-03-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_sga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictogram',
            name='human_tag',
            field=models.IntegerField(choices=[(5, 'Danger'), (1, 'Attention')], db_index=True, default=0),
        ),
    ]
